[project]
name = "afterimage"
version = "0.1.2"
keywords = ["afterimage", "synthetic", "dataset-generation", "synthetic-dataset"]
authors = [
    { name = "Yusuf Sarıgöz", email = "yusufsarigoz@gmail.com"}
]
description = "Create synthetic datasets based on your documents"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "google-generativeai>=0.8.3",
    "grpcio==1.67.1",
    "letsearch-client>=0.1.1",
    "pydantic>=2.10.4",
    "tqdm>=4.67.1",
]

[project.urls]
homepage = "https://github.com/monatis/afterimage"
project = "https://github.com/monatis/afterimage"
repository = "https://github.com/monatis/afterimage"

