[project]
name = "afterimage"
version = "0.7.0"
keywords = ["afterimage", "synthetic", "dataset-generation", "synthetic-dataset"]
authors = [
    { name = "Yusuf Sarıgöz", email = "yusuf@altai.dev"}
]
description = "Create synthetic datasets based on your documents"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "grpcio==1.67.1",
    "letsearch-client>=0.1.1",
    "pydantic>=2.10.4",
    "tqdm>=4.67.1",
    "filelock",
    "qdrant-client",
    "sentence-transformers",
    "langdetect>=1.0.9",
    "pandas>=2.0.0",
    "openpyxl>=3.0.0",
    "pyarrow>=14.0.1",
    "seaborn>=0.12.0",
    "matplotlib>=3.7.0",
    "google-genai>=1.14.0",
]

[project.urls]
homepage = "https://github.com/monatis/afterimage"
project = "https://github.com/monatis/afterimage"
repository = "https://github.com/monatis/afterimage"

