from enum import Enum
from typing import Any, List, Optional, Generic, TypeVar, Dict
from pydantic import BaseModel, Field

T = TypeVar("T")
import uuid


class GradeSchema(str, Enum):
    PERFECT = "perfect"
    GOOD = "good"
    NEEDS_IMPROVEMENT = "needs_improvement"
    BAD = "bad"
    NOT_ACCEPTABLE = "not_acceptable"


class EvaluationEntrySchema(BaseModel):
    feedback: str
    score: float


class EvaluationSchema(BaseModel):
    coherence: EvaluationEntrySchema
    factuality: EvaluationEntrySchema
    grounding: EvaluationEntrySchema
    helpfulness: EvaluationEntrySchema
    relevance: EvaluationEntrySchema
    overall_grade: GradeSchema


class Role(str, Enum):
    USER = "user"
    ASSISTANT = "assistant"


class ConversationEntry(BaseModel):
    role: Role
    content: str


class Conversation(BaseModel):
    conversations: List[ConversationEntry]
    metadata: Optional[dict[str, Any]] = None


class ConversationWithContext(Conversation):
    instruction_context: Optional[str] = None
    response_context: Optional[str] = None
    persona: Optional[str] = None


class EvaluatedConversationWithContext(ConversationWithContext):
    evaluation: EvaluationSchema
    final_score: Optional[float] = 0.0


class PersonaEntry(BaseModel):
    """Represents a set of generated personas for a source document."""

    descriptions: list[str] = Field(..., description="List of persona descriptions")
    metadata: dict = Field(default_factory=dict, description="Any associated metadata")


class StructuredGenerationRow(BaseModel, Generic[T]):
    """Represents a single row of structured generation, including metadata."""

    instruction: str = Field(
        ..., description="The user instructions/prompt used to generate the output."
    )
    context: Optional[str] = Field(
        None, description="The context provided to the model."
    )
    persona: Optional[str] = Field(
        None, description="The persona adopted by the respondent."
    )
    output: T = Field(..., description="The structured output generated by the model.")
    metadata: Dict[str, Any] = Field(
        default_factory=dict, description="Metadata about the generation."
    )


class GeneratedResponsePrompt(BaseModel):
    """Output of RespondentPromptModifier."""

    prompt: str = Field(..., description="Modified respondent prompt")
    context: Optional[str] = Field(
        None, description="Context used in respondent prompt"
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata about respondent promp generation",
    )


class Document(BaseModel):
    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Id of the document. Autogenerated if not specified",
    )
    text: Optional[str] = None
    personas: list[PersonaEntry] = Field(
        default_factory=list, description="List of persona generations"
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Any associated metadata"
    )
